apiVersion: v1
kind: Config
clusters:
- name: mock-cluster
  cluster:
    server: https://127.0.0.1:8443
    insecure-skip-tls-verify: true
contexts:
- name: mock-context
  context:
    cluster: mock-cluster
    user: mock-user
    namespace: payment-prod
current-context: mock-context
users:
- name: mock-user
  user:
    token: fake-token-for-demo
